Feature/epi 40 wrap asio
epitech-mirroring/R-Type-Reborn pull request #10
Opened 2024-10-01 17:19 UTC by 6im0n

This pull request includes significant changes to the build system, documentation, and network module of the project. The most important changes include the removal of the top-level `CMakeLists.txt` file, the addition of a comprehensive guide for installing `vcpkg`, and the implementation of the network client and server classes.

### Build System Changes:
* [`CMakeLists.txt`](diffhunk://#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20aL1-L13): Removed the top-level CMake configuration file.
* [`src/CMakeLists.txt`](diffhunk://#diff-148715d6ea0c0ea0a346af3f6bd610d010d490eca35ac6a9b408748f7ca9e3f4L1-L5): Removed the source file listing for the main executable.
* [`src/network/CMakeLists.txt`](diffhunk://#diff-eac9acce65b7952c47b3eb85578f05e7940aca43de1c1c2d202a20e27adb9406R1-R16): Added a new CMake configuration for the `Rtype-network` library, including source and header files.

### Documentation Changes:
* [`documentation/vcpkg_installation_guide.md`](diffhunk://#diff-df2755d296edc179d085886168d5e37aa7bc2887b151c4a44553df3298f543ebR1-R106): Added a detailed installation guide for `vcpkg` on Windows, Linux, and macOS.

### Network Module Implementation:
* [`src/network/client/Client.cpp`](diffhunk://#diff-ca0eef843161a1a7341a6970a29de77ba6c52acb60182df7931461cc082e51cdR1-R38): Implemented the `Client` class with methods for sending and receiving data over UDP.
* [`src/network/client/Client.hpp`](diffhunk://#diff-82184981fbfd14bdc53c351dc1bc4a3f0db0da15e21b44259a6bd1299a2235efR1-R31): Defined the `Client` class interface.
* [`src/network/server/Server.cpp`](diffhunk://#diff-d085b2cdabf72993c27ef0e4e28235e9f0a4d95eba20d3ec2ebccdbf9d04cc55R1-R53): Implemented the `Server` class with methods for handling client connections and data transmission.
* [`src/network/server/Server.hpp`](diffhunk://#diff-ce82f6a0019e8ee9c5f566fc88de94cf71cc814f8a7e30467e50990c0f1c7117R1-R34): Defined the `Server` class interface.

### Test Changes:
* [`tests/client/main.cpp`](diffhunk://#diff-a10939fe2594bfc711d6cc04c20f2b59ee86c350c13973fced3c50ebc58841d4L9-R13): Renamed from `src/main.cpp` and updated to include the client header file.
* [`tests/server/main.cpp`](diffhunk://#diff-35a05a3da403f39b990969e0102370c5ca3447343c869d5a689305b77fe53951R1-R15): Added a new test file for the server implementation.

2024-10-02 11:33 UTC, landryarki approved these changes
:100:

2024-10-12 17:16 UTC, Marius-P1 requested changes
Some little changes

2024-10-12 17:16 UTC, Marius-P1 commented on CMakeLists.txt
> +#add_subdirectory(tests)
```suggestion
```

2024-10-12 17:16 UTC, Marius-P1 commented on CMakeLists.txt
> +include_directories(network)
I think that should be before the add_sub client and server

2024-10-12 17:16 UTC, Marius-P1 commented on network/CMakeLists.txt
> +cmake_minimum_required(VERSION 3.5)
You don't need to write it again, it's already in the root CMakeLists
```suggestion
```

2024-10-12 17:16 UTC, Marius-P1 commented on network/client/Client.cpp
> +
```suggestion
```

2024-10-12 17:16 UTC, Marius-P1 commented on network/client/Client.cpp
> +        return;
All your error should use throw (except if it's not a critical error)
Create a NetworkException that inherit from IError which is present in includes/stellarforge/common

2024-10-12 17:16 UTC, Marius-P1 commented on network/client/Client.cpp
> +        return;
All your error should use throw (except if it's not a critical error)

2024-10-12 17:16 UTC, Marius-P1 commented on network/server/InternalMessage/ClientConnected.hpp
> +    std::uint8_t _id; ///< The client ID
Why not use int

2024-10-12 17:16 UTC, Marius-P1 commented on network/server/Server.cpp
> +            int8_t id = 0;
Use int for id
```suggestion
            int id = 0;
```

2024-10-12 17:16 UTC, Marius-P1 commented on server/CMakeLists.txt
> +
```suggestion
```

2024-10-12 17:16 UTC, Marius-P1 commented on server/CMakeLists.txt
> +target_link_libraries(r-type_server PRIVATE rtype::network)
This should be under the other target_link_libraries and not under the source files

2024-10-12 19:17 UTC, Marius-P1 approved these changes
:ok_hand:

2024-10-12 19:17 UTC, merged