:memo: Create the project README
epitech-mirroring/R-Type-Reborn pull request #5
Opened 2024-09-19 16:31 UTC by Marius-P1

This PR introduces the README.md file, which serves as the primary documentation for the R-Type: Reborn project.
The README provides a clear and concise overview of the project, including :

- Project purpose and structure
- Dependencies, requirements, and supported platforms
- Build and usage instructions
- Links to the Game Engine (Stellar Forge) and Game Editor (Orion Editor)
- Authors and contact details

This README will be the central entry point for the entire project.

2024-09-19 22:44 UTC, RenardFute requested changes
As good as #6 but you'r also targeting main!
![not-again-facepalm](https://github.com/user-attachments/assets/6ca56d00-6edf-4593-b28d-3e27885bce05)

2024-09-20 11:15 UTC, Marius-P1 commented
Edited @RenardFute :sweat_smile:

2024-09-20 11:29 UTC, RenardFute approved these changes

2024-09-20 14:31 UTC, 6im0n approved these changes
Nice looking readme :+1:

2024-09-20 14:38 UTC, merged