:memo: study of different architectures of the engine
epitech-mirroring/R-Type-Reborn pull request #7
Opened 2024-09-23 15:54 UTC by landryarki

comparing ECS and OOP based game engine

2024-09-24 14:59 UTC, RenardFute requested changes
It would be nice if you can add or update the final sentence to explain our final choice (here OOP) and why we made that choice.

2024-09-26 12:39 UTC, 6im0n reviewed
Good benchmark ! Just add a litle conclusion to introduce the OOP, and the schematics of the architecture :ok_hand:

2024-10-10 13:33 UTC, 6im0n requested changes

2024-10-10 13:33 UTC, 6im0n commented on documentation/benchmarks/game_engine/architecture_study.md
> +Source: [GameDev Stack Exchange](https://gamedev.stackexchange.com/questions/200076/i-dont-get-why-ecs-is-considered-more-performant-than-oop)
```suggestion

The flowchart of our architecture 
```mermaid
flowchart LR

    scene_manager[scene manager]
    event_sys[event system]
    object_management[object manager]
    config_reader[config reader]
    factory[factory]
    
    subgraph Game_engine
        scene_manager -- Has[1] --> object_management 
        object_management <--> event_sys 
        object_management --Has[?]--> factory 
        subgraph Bootstrap
            config_reader
        end
        Bootstrap --Initialize--> object_management
        Bootstrap --Feed--> factory
        Bootstrap --Initialize--> event_sys
        Bootstrap --Initialize--> scene_manager
    end

    scene[scene]
    object[object]
    components[components]
    sprites[sprites]

    UI_text[UI text]
    UI_buttons[UI buttons]
    CppMonoBehaviours[CppMonoBehaviours]
    rigid_body[rigid body]
    scripts[scripts]
    animated_sprites[animated sprites]


    Game_engine --Contain[?]--> scene 
    scene --Contain[N]--> object
    object --Contain[N]--> components
    components -.-> sprites
    subgraph Components
        sprites -.-> animated_sprites
        components -.-> UI_text
        components -.-> UI_buttons
        components -.-> CppMonoBehaviours
        components -.-> scripts
        components -.-> rigid_body
    end
    scripts --Can access--> Game_engine
    CppMonoBehaviours --Can access--> Game_engine

```
  Source: [GameDev Stack Exchange](https://gamedev.stackexchange.com/questions/200076/i-dont-get-why-ecs-is-considered-more-performant-than-oop)
```

2024-10-10 13:55 UTC, Marius-P1 approved these changes
:ok_hand:

2024-10-10 13:56 UTC, RenardFute approved these changes

2024-10-10 14:12 UTC, 6im0n approved these changes
Good for me !

2024-10-10 14:50 UTC, merged